theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-end
  home:
    head:
      title: site
  logo:
    header: "/assets/images/logo-horizontal.svg"
    footer: "/assets/images/logo.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  pages:
    index:
      options:
        summary: false
  posts:
    index:
      layout: grid
  image_sizes:
    sections:
      organizations:
        item:
          mobile:   400
          tablet:   500
          desktop:  600