theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-end
  home:
    head:
      title: site
  logo:
    header: "/assets/images/logo-horizontal.svg"
    footer: "/assets/images/logo.svg"
